CREATE TABLE left_point
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position          INTEGER NOT NULL,
    number_of_updates INTEGER NOT NULL
);

CREATE TABLE right_point
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position          INTEGER NOT NULL,
    number_of_updates INTEGER NOT NULL
);

CREATE TABLE line
(
    id                  UUID PRIMARY KEY,
    version             BIGINT       NOT NULL DEFAULT 0,
    left_id             BIGINT       NOT NULL,
    right_id            BIGINT       NOT NULL,
    updated_at          TIMESTAMP,
    business_partner_id VARCHAR(255) NOT NULL,

    CONSTRAINT fk_line_left FOREIGN KEY (left_id) REFERENCES left_point (id),
    CONSTRAINT fk_line_right FOREIGN KEY (right_id) REFERENCES right_point (id)
--
--     -- 1:1 with points (matches @OneToOne on Line.left / Line.right). Also
--     -- doubles as an index on each FK, so the FK lookups stay cheap.
--     CONSTRAINT uq_line_left UNIQUE (left_id),
--     CONSTRAINT uq_line_right UNIQUE (right_id),
);

-- Generic record of "a request with this Idempotency-Key was already handled", written by
-- IdempotencyFilter -- not specific to Line at all (any /lines/** request carrying the header
-- goes through it), so unlike manual_operation below it isn't even scoped to a line id. Not FK'd
-- to anything for the same reason the old line-specific version wasn't: a replay record should
-- outlive whatever resource it was originally applied to.
CREATE TABLE idempotency_record
(
    id               VARCHAR(255) PRIMARY KEY,
    fingerprint      VARCHAR(255) NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    response_status  INTEGER,
    response_headers CLOB,
    response_body    BLOB,
    created_at       TIMESTAMP    NOT NULL,
    completed_at     TIMESTAMP
);

-- IdempotencyHousekeeping's cleanup cron is guarded by ShedLock so only one instance runs it when
-- this app is scaled horizontally. Shape matches jeap-messaging-outbox's own shedlock table
-- exactly (see that library's docs), even though this repo doesn't depend on it, for consistency
-- with the wider jeap ecosystem's convention.
CREATE TABLE shedlock
(
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);

-- Same reasoning as idempotency_key above: not FK'd to line, so this audit trail survives a
-- later deletion of the line it describes.
CREATE TABLE manual_operation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id      UUID         NOT NULL,
    operation    VARCHAR(255) NOT NULL,
    detail       VARCHAR(255) NOT NULL,
    performed_by VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP    NOT NULL
);
