CREATE TABLE left_point
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position          INTEGER NOT NULL,
    number_of_updates INTEGER NOT NULL
);

CREATE TABLE right_point
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position          INTEGER NOT NULL,
    number_of_updates INTEGER NOT NULL
);

CREATE TABLE line
(
    id                  UUID PRIMARY KEY,
    version             BIGINT       NOT NULL DEFAULT 0,
    left_id             BIGINT       NOT NULL,
    right_id            BIGINT       NOT NULL,
    updated_at          TIMESTAMP,
    business_partner_id VARCHAR(255) NOT NULL,

    CONSTRAINT fk_line_left FOREIGN KEY (left_id) REFERENCES left_point (id),
    CONSTRAINT fk_line_right FOREIGN KEY (right_id) REFERENCES right_point (id)
--
--     -- 1:1 with points (matches @OneToOne on Line.left / Line.right). Also
--     -- doubles as an index on each FK, so the FK lookups stay cheap.
--     CONSTRAINT uq_line_left UNIQUE (left_id),
--     CONSTRAINT uq_line_right UNIQUE (right_id),
);

-- Not FK'd to line: a record of "this Idempotency-Key was already applied" should outlive
-- the line it was applied to (e.g. the line could later be deleted).
CREATE TABLE idempotency_key
(
    id          UUID PRIMARY KEY,
    fingerprint VARCHAR(255) NOT NULL
);

-- Same reasoning as idempotency_key above: not FK'd to line, so this audit trail survives a
-- later deletion of the line it describes.
CREATE TABLE manual_operation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id      UUID         NOT NULL,
    operation    VARCHAR(255) NOT NULL,
    detail       VARCHAR(255) NOT NULL,
    performed_by VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP    NOT NULL
);
